trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 5.0.x

- script: dotnet --info
  displayName: "dotnet info"
- script: dotnet restore
  displayName: "dotnet restore"
- script: dotnet build -c Release
  displayName: "dotnet build"