trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

pool:
  vmImage: 'windows-latest'

variables:
- group: nuget

steps:
- task: UseDotNet@2
  displayName: 'Use .NET sdk'
  inputs:
    packageType: sdk
    version: 8.0.x

- script: dotnet --info
  displayName: "dotnet info"
- script: dotnet restore
  displayName: "dotnet restore"
- script: dotnet build -c Release
  displayName: "dotnet build"
- powershell: ./build.ps1
  displayName: 'Powershell Script'
  env:
    Nuget__ApiKey: $(nugetApiKey)
    Nuget__SourceUrl: $(nugetSourceUrl)